# -*- coding: utf-8 -*-
"""guessing game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJMc0Q6VHhxPSCTbgKUfhWW9iScrM0YB
"""

import random

num = random.randint(1, 199)
guess = None

while guess != num:
      guess = input("Guess a number between 1 and 199 ")
      guess = int(guess)

      if guess == num:
        print("Congratulations! You guessed the number!")
        break
      elif guess < num:
          print("Too low! Try again.")
      elif guess > num:
         print("Too high! Try again.")